### PR TITLE
Add `profiler` option to `create_trainer`

### LINKED ISSUE #358: Trainer: Add an option to enable profiling in Handler config
Add an option to automatically wrap training loop with with `torch.cuda.profiler.profile()` and `torch.autograd.profiler.emit_nvtx()` (when CUDA is enabled).

### PR DESCRIPTION
**Pull request by asi1024**
Close #358

### CODE REVIEW

**Review by kmaehashi — CHANGES_REQUESTED** [review]
LGTM overall! could you fix conflicts?

**Comment by asi1024** [comment]
note: [9ac6940](https://github.com/pfnet/pytorch-pfn-extras/pull/527/commits/9ac69406b17662d7256241fa52e91a898dee8c37) can be reverted after torch 1.8 is dropped

**Review by kmaehashi — DISMISSED** [review]

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
