### PR TITLE
Make autoload fault tolerant

### PR DESCRIPTION
**Pull request by emcastillo**
Needs discussion

In some situations, temporal snapshot files might be found instead of final ones,
If only such files exist, is it reasonable to resume from them? In scenarios when training is automatically resumed after a fault
this can be a good idea to not waste computing resources.

Should we control this behavior with a keyword argument for snapshot? (I think this is probably the best option)

### CODE REVIEW

**Comment by dhgrs** [comment]
Please let me know, why is this PR closed? Are you working on it in other issues or PRs?

**Comment by emcastillo** [comment]
Sorry, we found a better way to address this in https://github.com/pfnet/pytorch-pfn-extras/pull/185 :)
Can you test master branch now?

**Comment by dhgrs** [comment]
I see, I didn't notice that #185 also fixes this issue. I'll check it.

**Comment by dhgrs** [comment]
I checked the PR. The PR doesn't change the way to find snapshots but changes the frequency where only temporary files exist. Now it very rarely happens to miss existing tmp snapshots. Then, what I can do to check more carefully is just using it in my workloads and making sure that the issue doesn't happen, right?

**Pull request closed without merging**
