### PR TITLE
Change to the test code directory of the handler/logic module.

### PR DESCRIPTION
**Pull request by linshokaku**

### CODE REVIEW

**Review by kmaehashi — APPROVED** [review]
LGTM!

**Review by kmaehashi — CHANGES_REQUESTED** [review]
Ah wait, `tests/pytorch_pfn_extras_tests/handler_tests/__init__.py` needs to be created when adding a new directory under tests.

**Comment by linshokaku** [comment]
Fixed it!

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
