### PR TITLE
Add torch 1.11 in CI matrix

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks, LGTM!
Testing https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/101667/

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/101703/

**Comment by kmaehashi** [comment]
Image built successfully, added webhook.

/test

**Comment by asi1024** [comment]
Updated branch protection.

**Pull request merged**
