### PR TITLE
Increase pytorch-pfn-extras.torch200-linux time_limit to avoid timeout

### PR DESCRIPTION
**Pull request by take-cheeze**

### CODE REVIEW

**Comment by take-cheeze** [comment]
Like https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/142297/

**Comment by kmaehashi** [comment]
I've removed `torch200` Docker image (which acts as a cache) and retriggered the test. Let's see if 1800 sec is sufficient.

https://console.cloud.google.com/artifacts/docker/pfn-artifactregistry/asia-northeast1/tmp-public-ci-dlfw/pytorch-pfn-extras-ci?project=pfn-artifactregistry

Please proceed to merge once the test passed!

**Review by kmaehashi — APPROVED** [review]

**Comment by take-cheeze** [comment]
It seems without docker image cache CI job takes about 17min when netwok status is normal
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294320
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294301

pip install takes 150 secs or more
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294320#L2229
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294301#L2223

apt install tooks 71 secs or 36 secs
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294320#L1330
https://ci.preferred.jp/pytorch-pfn-extras.torch200-linux/144050/294301#L1324

**Pull request merged**
