### PR TITLE
Fix test combinations

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
/test

https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/76141/

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
`pytorch-pfn-extras.torch17-win` failed as expected. (others should pass)

**Comment by kmaehashi** [comment]
Test failures will be fixed in separate PRs.

**Pull request merged**
