### PR TITLE
Test sdist build

### PR DESCRIPTION
**Pull request by kmaehashi**
I also expect this PR to fix the coverage reporting.

### CODE REVIEW

**Comment by emcastillo** [comment]
Is this PR ready?

**Comment by kmaehashi** [comment]
Test passed and coverage is now rendered correctly!

https://storage.googleapis.com/chainer-artifacts-pfn-public-ci/pytorch-pfn-extras/pytest-cov/95329/htmlcov/index.html

**Review by take-cheeze — APPROVED** [review]

**Review by emcastillo — APPROVED** [review]
LGTM!! Thanks!

**Pull request merged**
