### PR TITLE
Treat warnings as error

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Fixed to avoid copying tensor using `torch.tensor`. `SystemError` issue (PyTorch bug) will be fixed in https://github.com/pytorch/pytorch/pull/44371

**Review by emcastillo — APPROVED** [review]

**Comment by take-cheeze** [comment]
As commented in https://github.com/pfnet/pytorch-pfn-extras/pull/64/files#issuecomment-689993407 following test cases still fail:
```
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_annotate - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will sto...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_apply_annotation - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it ...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_scoped_anchor - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
FAILED tests/pytorch_pfn_extras_tests/onnx/test_export_testcase.py::test_backward_multiple_input - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
```
It's caused by ONNX and PyTorch so maybe these need to be ignored

**Comment by take-cheeze** [comment]
Seems this was closed with comment of https://github.com/pfnet/pytorch-pfn-extras/pull/64

**Pull request merged**
