### PR TITLE
Update PyTorch installation in nightly test workflow

### LINKED ISSUE #807: Nightly CI failure
Looks the problem is related to mpmath.

https://github.com/NVIDIA/TensorRT-LLM/pull/1146
https://pypi.org/project/mpmath/1.4.0a0/

(thanks @take-cheeze for investigation)

### PR DESCRIPTION
**Pull request by linshokaku**
close #807

### CODE REVIEW

**Comment by linshokaku** [comment]
https://github.com/linshokaku/pytorch-pfn-extras/actions/runs/8091091245
I have confirmed the implementation on the forked repository.

**Comment by take-cheeze** [comment]
Seems it's installing nightly torch correctly! : https://github.com/linshokaku/pytorch-pfn-extras/actions/runs/8091091245/job/22109618149#step:4:74

**Comment by kmaehashi** [comment]
Also confirmed `mpmath-1.3.0` is used. LGTM!

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
