### PR TITLE
Fix TensorBoard to no-op if TensorBoard is unavailable

### LINKED ISSUE #155: Make TensorBoardWriter no-op if tensorboard is not available

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #155. ~Depends on #158~ (merged).
I think this is better when reusing experiment codes.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Rebased.
/test

**Comment by kmaehashi** [comment]
Hmm seems it hangs at the end of epoch? Let me test locally...

**Comment by emcastillo** [comment]
Depends on #433

**Comment by kmaehashi** [comment]
Thanks! LGTM :+1:

**Pull request merged**
