### PR TITLE
pytorch-ignote 0.4.3 dropped Py35 support

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
manually triggered docker image generation test: https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/68321/

**Comment by take-cheeze** [comment]
Maybe this line needs fix too: https://github.com/pfnet/pytorch-pfn-extras/blob/ba0aedebd153914726e87c56d45f720ea3c2de7f/.flexci/windows/test.ps1#L32

**Review by emcastillo — APPROVED** [review]

**Comment by kmaehashi** [comment]
@take-cheeze Thanks, but on Windows, Python 3.5 is not tested. So it won't be needed.

**Comment by emcastillo** [comment]
torch15-linux is using py35 :(
https://ci.preferred.jp/pytorch-pfn-extras.torch15-linux/68318/

**Comment by kmaehashi** [comment]
Oops but I found another problem: https://github.com/pfnet/pytorch-pfn-extras/pull/114/files

> torch15-linux is using py35 :(
> https://ci.preferred.jp/pytorch-pfn-extras.torch15-linux/68318/

I think the docker image is now updated: https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/68321/
Let's rerun the test.

/test

**Comment by kmaehashi** [comment]
Test passed!

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
CI is unrelated (numpy 1.20)

**Pull request merged**
