### PR TITLE
Use pysen and enable mypy check

### PR DESCRIPTION
**Pull request by asi1024**
Part of #162.

Added mypy test to flexCI configuration and made small fixes to pass the test. I'm planning to send another PR for further type annotations after this PR.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Discussions:
- Introduce pysen and follow mypy option generated.
- Do not add type annotation to tests, because it is difficult to annotate parameterize tests and tests using mock, so we won't annotate tests. Increase the coverage of example and add types there to detect typing errors.

**Comment by asi1024** [comment]
Introduced pysen (136414a).
```
Found 1058 errors in 57 files (checked 74 source files)
```

**Comment by asi1024** [comment]
@kmaehashi PTAL!

**Comment by kmaehashi** [comment]
Could you remove package_data from setup.py as well?

**Comment by asi1024** [comment]
@kmaehashi Fixed!

**Pull request merged**
