### PR TITLE
Remove `examples` from `pyproject.toml`

### PR DESCRIPTION
**Pull request by emcastillo**
It is quite annoying to have to go through all these known errors when looking the mypy output for other files

### CODE REVIEW

**Comment by kmaehashi** [comment]
How about removing example from pyproject.yaml?

**Comment by emcastillo** [comment]
Do we want to fix annotations of these files?

**Comment by kmaehashi** [comment]
I'm thinking of checking examples and test codes with￼ allow-untyped-defs so that we can verify the correctness of types in PPE code base, without adding type annotations to examples and tests.

**Pull request merged**
