### PR TITLE
Make Extension typed

### PR DESCRIPTION
**Pull request by asi1024**
Depends on #179.

TODO: Remaining errors
```
pytorch_pfn_extras/training/extension.py:183: error: Property "default_name" defined in "Extension" is read-only  [misc]
pytorch_pfn_extras/training/extension.py:185: error: Cannot assign to a method  [assignment]
pytorch_pfn_extras/training/extension.py:185: error: Incompatible types in assignment (expression has type "Optional[Callable[[], None]]", variable has type "Callable[[], None]")  [assignment]
pytorch_pfn_extras/training/extension.py:186: error: Cannot assign to a method  [assignment]
pytorch_pfn_extras/training/extension.py:186: error: Incompatible types in assignment (expression has type "Optional[Callable[[ExtensionsManager, Exception, TracebackType], None]]", variable has type "Callable[[ExtensionsManager, Exception, TracebackType], None]")  [assignment]
pytorch_pfn_extras/training/extension.py:187: error: Cannot assign to a method  [assignment]
pytorch_pfn_extras/training/extension.py:187: error: Incompatible types in assignment (expression has type "Optional[Callable[[ExtensionsManager], None]]", variable has type "Callable[[ExtensionsManager], None]")  [assignment]
```

### CODE REVIEW

**Comment by kmaehashi** [comment]
#179 got merged! Could you rebase? @asi1024

**Comment by asi1024** [comment]
PTAL!

**Review by emcastillo — APPROVED** [review]
LGTM!

**Comment by kmaehashi** [comment]
@asi1024 Could you check test failures?

**Comment by emcastillo** [comment]
AttributeError: module 'pytorch_pfn_extras.training.extension' has no attribute 'ExtensionLike'

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
