### PR TITLE
Support Python 3.10

### LINKED ISSUE #386: Support Python 3.10
Need to add CI after PyTorch supports it.

### PR DESCRIPTION
**Pull request by emcastillo**
Test PyTorch 1.12 with Python 3.10

Fixes #386

Pending, no Python 3.10 support for onnxruntime

### CODE REVIEW

**Comment by kmaehashi** [comment]
ONNX Runtime 1.12.1 (Aug 5) added support for Pytohn 3.10.

**Comment by emcastillo** [comment]
Prep images

https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/109647/

**Comment by emcastillo** [comment]
Images were rebuilt
https://ci.preferred.jp/pytorch-pfn-extras.prep-linux/109857/

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
