### PR TITLE
use latest setuptools

### PR DESCRIPTION
**Pull request by linshokaku**

### CODE REVIEW

**Review by kmaehashi — DISMISSED** [review]

**Comment by kmaehashi** [comment]
Please merge after resolving conflict and confirming test pass.

**Comment by kmaehashi** [comment]
Tests looks failing :eyes:

**Comment by linshokaku** [comment]
PTAL
The test for torch==1.10 will be dropped in https://github.com/pfnet/pytorch-pfn-extras/pull/845.

**Comment by linshokaku** [comment]
@kmaehashi PTAL

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
