### PR TITLE
Support torch 2.2

### PR DESCRIPTION
**Pull request by take-cheeze**
- [ ] Add `pytorch-pfn-extras.torch202-win` to CI trigger after merge
- [ ] Add CI jobs to required stuff after merge

### CODE REVIEW

**Comment by take-cheeze** [comment]
https://ci.preferred.jp/pytorch-pfn-extras.torch202-win/155655/

**Comment by take-cheeze** [comment]
https://ci.preferred.jp/pytorch-pfn-extras.torch202-win/155655/

**Comment by take-cheeze** [comment]
https://ci.preferred.jp/pytorch-pfn-extras.torch202-linux/155683/

**Review by linshokaku — APPROVED** [review]
LGTM
Thanks!!

**Pull request merged**
