### PR TITLE
Fix onnx warnings when no training is set

### PR DESCRIPTION
**Pull request by emcastillo**
Should fix #57 issues in CI

### CODE REVIEW

**Comment by take-cheeze** [comment]
This reduce a lot! But there is few still failing:
```
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_annotate - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will sto...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_apply_annotation - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it ...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_scoped_anchor - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
FAILED tests/pytorch_pfn_extras_tests/onnx/test_export_testcase.py::test_backward_multiple_input - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
```

**Review by take-cheeze — APPROVED** [review]
LGTM :+1: 
Maybe it's more easiter to handle `training` argument with `_helper` method in: https://github.com/pfnet/pytorch-pfn-extras/pull/64/files#diff-191c558212029f4f7b2cc6e8dd07d57aR54

**Comment by emcastillo** [comment]
I think we can't do anything about these
```
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_annotate - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will sto...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_apply_annotation - DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it ...
FAILED tests/pytorch_pfn_extras_tests/onnx/test_annotate.py::test_scoped_anchor - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
FAILED tests/pytorch_pfn_extras_tests/onnx/test_export_testcase.py::test_backward_multiple_input - SystemError: <method '__bool__' of 'torch._C._TensorBase' objects> returned a result with an error set
```

**Comment by take-cheeze** [comment]
Yeah, those need to be ignored...

**Comment by emcastillo** [comment]
Done, PTAL :)

**Review by take-cheeze — APPROVED** [review]
Thank you for update! :+1: 
I've confirmed that this works with #57 !

**Comment by emcastillo** [comment]
merge please :)

**Comment by take-cheeze** [comment]
Sorry I don't have permission to merge... 
Please give me the permission for it  :bow:

**Pull request merged**
