### PR TITLE
Bump to PyTorch 1.7.0

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by emcastillo** [comment]
apparently there are only docker images for cuda11? https://hub.docker.com/r/pytorch/pytorch/tags

**Comment by kmaehashi** [comment]
/test

`test_extended_sequential.py` taking 20 minutes... Let me retest and see what happens.

**Comment by kmaehashi** [comment]
Failing with the same error... I'll check if it works locally.

**Comment by take-cheeze** [comment]
onnx warning should be fixed by: https://github.com/kmaehashi/pytorch-pfn-extras/pull/1

**Comment by emcastillo** [comment]
LOL
E   UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDAFunctions.cpp:100.)

**Comment by emcastillo** [comment]
still not updated :(

**Pull request merged**
