### PR TITLE
[pfto] Fix empty list handling in make_attribute

### PR DESCRIPTION
**Pull request by take-cheeze**
Ref https://github.com/onnx/onnx/issues/5216

### CODE REVIEW

**Comment by hvy** [comment]
This would be great to have merged. Is there anything I could do to help?

**Review by xuzijian629 — APPROVED** [review]
LGTM!

**Comment by xuzijian629** [comment]
sorry for no response for a long time 🙇

**Comment by hvy** [comment]
Thanks so much!

**Pull request merged**
