### PR TITLE
default transform_model friendlier

### PR DESCRIPTION
**Pull request by yuyu2172**
I find it cumbersome to set transform_model when using DDP.

### CODE REVIEW

**Comment by emcastillo** [comment]
Thank you!
Could you also please set this as the default for `ExtensionsManager.__init__`?

**Comment by yuyu2172** [comment]
Thanks for a review.
I updated the code.

**Review by emcastillo — APPROVED** [review]
Thank you, this looks great :)

**Comment by emcastillo** [comment]
can you rebase please?

**Comment by yuyu2172** [comment]
Got it. Done.

**Pull request merged**
